### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by musicderp** [Jellayy/atlantis-testing#5]
I do not know what this is please explain what it is thank you

**Comment by Jellayy** [comment]
Thank you for your extremely detailed bug report here is your answer good open source contributor:

Am testing selfhosting this service https://www.runatlantis.io/ for work

If you look at this PR here: https://github.com/Jellayy/atlantis-testing/pull/4
And this workflow here: https://app.terraform.io/app/jellayy/workspaces/atlantis-testing/runs/run-JYeMetSdGgvSNC9c

The bot auto runs plans to deploy this module I made: https://github.com/Jellayy/terraform-aws-ec2-apache to aws

The bot is very bad and errors quite a lot

**Comment by Jellayy** [comment]
inactivity, also ur bad
